openapi: 3.0.2
info:
  title: Games-API
  version: 1.0.0
  description: A brand new API with no content. Go nuts!
paths:
  /games:
    description: ''
    get:
      tags:
        - games
      responses:
        '200':
          description: Returns a list of games
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GameList'
      summary: Get a list of all games.
      description: Returns a list of all games in API
    post:
      requestBody:
        description: 'A new game to be created '
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewGame'
        required: true
      tags:
        - new-game
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewGame'
          description: Game is created
        '400':
          description: One or all params are missing
      summary: Creates a game
      description: Creates a new game
  /games/{id}:
    get:
      tags:
        - details
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the game to get
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
          description: Returns full details of a given game by ID
        '404':
          description: Game was not found in games array.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      summary: Get full details of a game
      description: Returns full details of a game by its ID
    delete:
      tags:
        - delete
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Numeric ID of the game to delete
      responses:
        '204':
          description: Game was deleted successfully
        '404':
          description: Game not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      summary: Delete game
      description: Delete a game by its ID
components:
  schemas:
    Error:
      title: Error
      type: object
      properties:
        error:
          type: string
      example:
        error: Error message.
    NewGame:
      title: NewGame
      type: object
      required:
        - price
        - name
      properties:
        name:
          type: string
        price:
          type: number
          format: float
      example:
        name: Tetris
        price: 0.99
    Game:
      title: Game
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: number
          format: float
      example:
        id: 1
        name: Witcher 3
        price: 29.99
    GameList:
      title: GameList
      type: array
      items:
        $ref: '#/components/schemas/Game'
